version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8020:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
